import os
import sys
import django

# Setup Django
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'space_and_beauty.settings')
django.setup()

from categories.models import Countries

# List of all 195 countries with their ISO codes, dial codes, and currency info
# Using flagcdn.com for flag images (free CDN)
# Each country has a unique code based on ISO 3166-1 alpha-2
COUNTRIES = [
    {"id": 1, "title": "Afghanistan", "code": "AF", "code2": "af", "dial_code": 93, "currency_type": "AFN"},
    {"id": 2, "title": "Albania", "code": "AL", "code2": "al", "dial_code": 355, "currency_type": "ALL"},
    {"id": 3, "title": "Algeria", "code": "DZ", "code2": "dz", "dial_code": 213, "currency_type": "DZD"},
    {"id": 4, "title": "Andorra", "code": "AD", "code2": "ad", "dial_code": 376, "currency_type": "€"},
    {"id": 5, "title": "Angola", "code": "AO", "code2": "ao", "dial_code": 244, "currency_type": "AOA"},
    {"id": 6, "title": "Antigua and Barbuda", "code": "AG", "code2": "ag", "dial_code": 1, "currency_type": "XCD"},
    {"id": 7, "title": "Argentina", "code": "AR", "code2": "ar", "dial_code": 54, "currency_type": "$"},
    {"id": 8, "title": "Armenia", "code": "AM", "code2": "am", "dial_code": 374, "currency_type": "AMD"},
    {"id": 9, "title": "Australia", "code": "AU", "code2": "au", "dial_code": 61, "currency_type": "$"},
    {"id": 10, "title": "Austria", "code": "AT", "code2": "at", "dial_code": 43, "currency_type": "€"},
    {"id": 11, "title": "Azerbaijan", "code": "AZ", "code2": "az", "dial_code": 994, "currency_type": "AZN"},
    {"id": 12, "title": "Bahamas", "code": "BS", "code2": "bs", "dial_code": 1, "currency_type": "BSD"},
    {"id": 13, "title": "Bahrain", "code": "BH", "code2": "bh", "dial_code": 973, "currency_type": "BHD"},
    {"id": 14, "title": "Bangladesh", "code": "BD", "code2": "bd", "dial_code": 880, "currency_type": "৳"},
    {"id": 15, "title": "Barbados", "code": "BB", "code2": "bb", "dial_code": 1, "currency_type": "BBD"},
    {"id": 16, "title": "Belarus", "code": "BY", "code2": "by", "dial_code": 375, "currency_type": "BYR"},
    {"id": 17, "title": "Belgium", "code": "BE", "code2": "be", "dial_code": 32, "currency_type": "€"},
    {"id": 18, "title": "Belize", "code": "BZ", "code2": "bz", "dial_code": 501, "currency_type": "BZD"},
    {"id": 19, "title": "Benin", "code": "BJ", "code2": "bj", "dial_code": 229, "currency_type": "XOF"},
    {"id": 20, "title": "Bhutan", "code": "BT", "code2": "bt", "dial_code": 975, "currency_type": "BTN"},
    {"id": 21, "title": "Bolivia", "code": "BO", "code2": "bo", "dial_code": 591, "currency_type": "BOB"},
    {"id": 22, "title": "Bosnia and Herzegovina", "code": "BA", "code2": "ba", "dial_code": 387, "currency_type": "BAM"},
    {"id": 23, "title": "Botswana", "code": "BW", "code2": "bw", "dial_code": 267, "currency_type": "BWP"},
    {"id": 24, "title": "Brazil", "code": "BR", "code2": "br", "dial_code": 55, "currency_type": "R$"},
    {"id": 25, "title": "Brunei", "code": "BN", "code2": "bn", "dial_code": 673, "currency_type": "BND"},
    {"id": 26, "title": "Bulgaria", "code": "BG", "code2": "bg", "dial_code": 359, "currency_type": "BGN"},
    {"id": 27, "title": "Burkina Faso", "code": "BF", "code2": "bf", "dial_code": 226, "currency_type": "XOF"},
    {"id": 28, "title": "Burundi", "code": "BI", "code2": "bi", "dial_code": 257, "currency_type": "BIF"},
    {"id": 29, "title": "Cabo Verde", "code": "CV", "code2": "cv", "dial_code": 238, "currency_type": "CVE"},
    {"id": 30, "title": "Cambodia", "code": "KH", "code2": "kh", "dial_code": 855, "currency_type": "KHR"},
    {"id": 31, "title": "Cameroon", "code": "CM", "code2": "cm", "dial_code": 237, "currency_type": "XAF"},
    {"id": 32, "title": "Canada", "code": "CA", "code2": "ca", "dial_code": 1, "currency_type": "C$"},
    {"id": 33, "title": "Central African Republic", "code": "CF", "code2": "cf", "dial_code": 236, "currency_type": "XAF"},
    {"id": 34, "title": "Chad", "code": "TD", "code2": "td", "dial_code": 235, "currency_type": "XAF"},
    {"id": 35, "title": "Chile", "code": "CL", "code2": "cl", "dial_code": 56, "currency_type": "$"},
    {"id": 36, "title": "China", "code": "CN", "code2": "cn", "dial_code": 86, "currency_type": "¥"},
    {"id": 37, "title": "Colombia", "code": "CO", "code2": "co", "dial_code": 57, "currency_type": "$"},
    {"id": 38, "title": "Comoros", "code": "KM", "code2": "km", "dial_code": 269, "currency_type": "KMF"},
    {"id": 39, "title": "Congo (Brazzaville)", "code": "CG", "code2": "cg", "dial_code": 242, "currency_type": "XAF"},
    {"id": 40, "title": "Congo (Kinshasa)", "code": "CD", "code2": "cd", "dial_code": 243, "currency_type": "CDF"},
    {"id": 41, "title": "Costa Rica", "code": "CR", "code2": "cr", "dial_code": 506, "currency_type": "CRC"},
    {"id": 42, "title": "Croatia", "code": "HR", "code2": "hr", "dial_code": 385, "currency_type": "€"},
    {"id": 43, "title": "Cuba", "code": "CU", "code2": "cu", "dial_code": 53, "currency_type": "CUP"},
    {"id": 44, "title": "Cyprus", "code": "CY", "code2": "cy", "dial_code": 357, "currency_type": "€"},
    {"id": 45, "title": "Czech Republic", "code": "CZ", "code2": "cz", "dial_code": 420, "currency_type": "CZK"},
    {"id": 46, "title": "Denmark", "code": "DK", "code2": "dk", "dial_code": 45, "currency_type": "kr"},
    {"id": 47, "title": "Djibouti", "code": "DJ", "code2": "dj", "dial_code": 253, "currency_type": "DJF"},
    {"id": 48, "title": "Dominica", "code": "DM", "code2": "dm", "dial_code": 1, "currency_type": "XCD"},
    {"id": 49, "title": "Dominican Republic", "code": "DO", "code2": "do", "dial_code": 1, "currency_type": "DOP"},
    {"id": 50, "title": "Ecuador", "code": "EC", "code2": "ec", "dial_code": 593, "currency_type": "$"},
    {"id": 51, "title": "Egypt", "code": "EG", "code2": "eg", "dial_code": 20, "currency_type": "EGP"},
    {"id": 52, "title": "El Salvador", "code": "SV", "code2": "sv", "dial_code": 503, "currency_type": "$"},
    {"id": 53, "title": "Equatorial Guinea", "code": "GQ", "code2": "gq", "dial_code": 240, "currency_type": "XAF"},
    {"id": 54, "title": "Eritrea", "code": "ER", "code2": "er", "dial_code": 291, "currency_type": "ERN"},
    {"id": 55, "title": "Estonia", "code": "EE", "code2": "ee", "dial_code": 372, "currency_type": "€"},
    {"id": 56, "title": "Eswatini", "code": "SZ", "code2": "sz", "dial_code": 268, "currency_type": "SZL"},
    {"id": 57, "title": "Ethiopia", "code": "ET", "code2": "et", "dial_code": 251, "currency_type": "ETB"},
    {"id": 58, "title": "Fiji", "code": "FJ", "code2": "fj", "dial_code": 679, "currency_type": "$"},
    {"id": 59, "title": "Finland", "code": "FI", "code2": "fi", "dial_code": 358, "currency_type": "€"},
    {"id": 60, "title": "France", "code": "FR", "code2": "fr", "dial_code": 33, "currency_type": "€"},
    {"id": 61, "title": "Gabon", "code": "GA", "code2": "ga", "dial_code": 241, "currency_type": "XAF"},
    {"id": 62, "title": "Gambia", "code": "GM", "code2": "gm", "dial_code": 220, "currency_type": "GMD"},
    {"id": 63, "title": "Georgia", "code": "GE", "code2": "ge", "dial_code": 995, "currency_type": "GEL"},
    {"id": 64, "title": "Germany", "code": "DE", "code2": "de", "dial_code": 49, "currency_type": "€"},
    {"id": 65, "title": "Ghana", "code": "GH", "code2": "gh", "dial_code": 233, "currency_type": "GHS"},
    {"id": 66, "title": "Greece", "code": "GR", "code2": "gr", "dial_code": 30, "currency_type": "€"},
    {"id": 67, "title": "Grenada", "code": "GD", "code2": "gd", "dial_code": 1, "currency_type": "XCD"},
    {"id": 68, "title": "Guatemala", "code": "GT", "code2": "gt", "dial_code": 502, "currency_type": "GTQ"},
    {"id": 69, "title": "Guinea", "code": "GN", "code2": "gn", "dial_code": 224, "currency_type": "GNF"},
    {"id": 70, "title": "Guinea-Bissau", "code": "GW", "code2": "gw", "dial_code": 245, "currency_type": "XOF"},
    {"id": 71, "title": "Guyana", "code": "GY", "code2": "gy", "dial_code": 592, "currency_type": "$"},
    {"id": 72, "title": "Haiti", "code": "HT", "code2": "ht", "dial_code": 509, "currency_type": "HTG"},
    {"id": 73, "title": "Holy See", "code": "VA", "code2": "va", "dial_code": 379, "currency_type": "€"},
    {"id": 74, "title": "Honduras", "code": "HN", "code2": "hn", "dial_code": 504, "currency_type": "HNL"},
    {"id": 75, "title": "Hungary", "code": "HU", "code2": "hu", "dial_code": 36, "currency_type": "HUF"},
    {"id": 76, "title": "Iceland", "code": "IS", "code2": "is", "dial_code": 354, "currency_type": "ISK"},
    {"id": 77, "title": "India", "code": "IN", "code2": "in", "dial_code": 91, "currency_type": "₹"},
    {"id": 78, "title": "Indonesia", "code": "ID", "code2": "id", "dial_code": 62, "currency_type": "Rp"},
    {"id": 79, "title": "Iran", "code": "IR", "code2": "ir", "dial_code": 98, "currency_type": "IRR"},
    {"id": 80, "title": "Iraq", "code": "IQ", "code2": "iq", "dial_code": 964, "currency_type": "IQD"},
    {"id": 81, "title": "Ireland", "code": "IE", "code2": "ie", "dial_code": 353, "currency_type": "€"},
    {"id": 82, "title": "Israel", "code": "IL", "code2": "il", "dial_code": 972, "currency_type": "₪"},
    {"id": 83, "title": "Italy", "code": "IT", "code2": "it", "dial_code": 39, "currency_type": "€"},
    {"id": 84, "title": "Jamaica", "code": "JM", "code2": "jm", "dial_code": 1, "currency_type": "$"},
    {"id": 85, "title": "Japan", "code": "JP", "code2": "jp", "dial_code": 81, "currency_type": "¥"},
    {"id": 86, "title": "Jordan", "code": "JO", "code2": "jo", "dial_code": 962, "currency_type": "JOD"},
    {"id": 87, "title": "Kazakhstan", "code": "KZ", "code2": "kz", "dial_code": 7, "currency_type": "KZT"},
    {"id": 88, "title": "Kenya", "code": "KE", "code2": "ke", "dial_code": 254, "currency_type": "KES"},
    {"id": 89, "title": "Kiribati", "code": "KI", "code2": "ki", "dial_code": 686, "currency_type": "$"},
    {"id": 90, "title": "Kuwait", "code": "KW", "code2": "kw", "dial_code": 965, "currency_type": "KWD"},
    {"id": 91, "title": "Kyrgyzstan", "code": "KG", "code2": "kg", "dial_code": 996, "currency_type": "KGS"},
    {"id": 92, "title": "Laos", "code": "LA", "code2": "la", "dial_code": 856, "currency_type": "LAK"},
    {"id": 93, "title": "Latvia", "code": "LV", "code2": "lv", "dial_code": 371, "currency_type": "€"},
    {"id": 94, "title": "Lebanon", "code": "LB", "code2": "lb", "dial_code": 961, "currency_type": "LBP"},
    {"id": 95, "title": "Lesotho", "code": "LS", "code2": "ls", "dial_code": 266, "currency_type": "LSL"},
    {"id": 96, "title": "Liberia", "code": "LR", "code2": "lr", "dial_code": 231, "currency_type": "$"},
    {"id": 97, "title": "Libya", "code": "LY", "code2": "ly", "dial_code": 218, "currency_type": "LYD"},
    {"id": 98, "title": "Liechtenstein", "code": "LI", "code2": "li", "dial_code": 423, "currency_type": "CHF"},
    {"id": 99, "title": "Lithuania", "code": "LT", "code2": "lt", "dial_code": 370, "currency_type": "€"},
    {"id": 100, "title": "Luxembourg", "code": "LU", "code2": "lu", "dial_code": 352, "currency_type": "€"},
    {"id": 101, "title": "Madagascar", "code": "MG", "code2": "mg", "dial_code": 261, "currency_type": "MGA"},
    {"id": 102, "title": "Malawi", "code": "MW", "code2": "mw", "dial_code": 265, "currency_type": "MWK"},
    {"id": 103, "title": "Malaysia", "code": "MY", "code2": "my", "dial_code": 60, "currency_type": "RM"},
    {"id": 104, "title": "Maldives", "code": "MV", "code2": "mv", "dial_code": 960, "currency_type": "MVR"},
    {"id": 105, "title": "Mali", "code": "ML", "code2": "ml", "dial_code": 223, "currency_type": "XOF"},
    {"id": 106, "title": "Malta", "code": "MT", "code2": "mt", "dial_code": 356, "currency_type": "€"},
    {"id": 107, "title": "Marshall Islands", "code": "MH", "code2": "mh", "dial_code": 692, "currency_type": "$"},
    {"id": 108, "title": "Mauritania", "code": "MR", "code2": "mr", "dial_code": 222, "currency_type": "MRU"},
    {"id": 109, "title": "Mauritius", "code": "MU", "code2": "mu", "dial_code": 230, "currency_type": "MUR"},
    {"id": 110, "title": "Mexico", "code": "MX", "code2": "mx", "dial_code": 52, "currency_type": "$"},
    {"id": 111, "title": "Micronesia", "code": "FM", "code2": "fm", "dial_code": 691, "currency_type": "$"},
    {"id": 112, "title": "Moldova", "code": "MD", "code2": "md", "dial_code": 373, "currency_type": "MDL"},
    {"id": 113, "title": "Monaco", "code": "MC", "code2": "mc", "dial_code": 377, "currency_type": "€"},
    {"id": 114, "title": "Mongolia", "code": "MN", "code2": "mn", "dial_code": 976, "currency_type": "MNT"},
    {"id": 115, "title": "Montenegro", "code": "ME", "code2": "me", "dial_code": 382, "currency_type": "€"},
    {"id": 116, "title": "Morocco", "code": "MA", "code2": "ma", "dial_code": 212, "currency_type": "MAD"},
    {"id": 117, "title": "Mozambique", "code": "MZ", "code2": "mz", "dial_code": 258, "currency_type": "MZN"},
    {"id": 118, "title": "Myanmar", "code": "MM", "code2": "mm", "dial_code": 95, "currency_type": "MMK"},
    {"id": 119, "title": "Namibia", "code": "NA", "code2": "na", "dial_code": 264, "currency_type": "$"},
    {"id": 120, "title": "Nauru", "code": "NR", "code2": "nr", "dial_code": 674, "currency_type": "$"},
    {"id": 121, "title": "Nepal", "code": "NP", "code2": "np", "dial_code": 977, "currency_type": "NPR"},
    {"id": 122, "title": "Netherlands", "code": "NL", "code2": "nl", "dial_code": 31, "currency_type": "€"},
    {"id": 123, "title": "New Zealand", "code": "NZ", "code2": "nz", "dial_code": 64, "currency_type": "$"},
    {"id": 124, "title": "Nicaragua", "code": "NI", "code2": "ni", "dial_code": 505, "currency_type": "NIO"},
    {"id": 125, "title": "Niger", "code": "NE", "code2": "ne", "dial_code": 227, "currency_type": "XOF"},
    {"id": 126, "title": "Nigeria", "code": "NG", "code2": "ng", "dial_code": 234, "currency_type": "₦"},
    {"id": 127, "title": "North Korea", "code": "KP", "code2": "kp", "dial_code": 850, "currency_type": "KPW"},
    {"id": 128, "title": "North Macedonia", "code": "MK", "code2": "mk", "dial_code": 389, "currency_type": "MKD"},
    {"id": 129, "title": "Norway", "code": "NO", "code2": "no", "dial_code": 47, "currency_type": "kr"},
    {"id": 130, "title": "Oman", "code": "OM", "code2": "om", "dial_code": 968, "currency_type": "OMR"},
    {"id": 131, "title": "Pakistan", "code": "PK", "code2": "pk", "dial_code": 92, "currency_type": "₨"},
    {"id": 132, "title": "Palau", "code": "PW", "code2": "pw", "dial_code": 680, "currency_type": "$"},
    {"id": 133, "title": "Palestine State", "code": "PS", "code2": "ps", "dial_code": 970, "currency_type": "₪"},
    {"id": 134, "title": "Panama", "code": "PA", "code2": "pa", "dial_code": 507, "currency_type": "$"},
    {"id": 135, "title": "Papua New Guinea", "code": "PG", "code2": "pg", "dial_code": 675, "currency_type": "PGK"},
    {"id": 136, "title": "Paraguay", "code": "PY", "code2": "py", "dial_code": 595, "currency_type": "PYG"},
    {"id": 137, "title": "Peru", "code": "PE", "code2": "pe", "dial_code": 51, "currency_type": "S/."},
    {"id": 138, "title": "Philippines", "code": "PH", "code2": "ph", "dial_code": 63, "currency_type": "₱"},
    {"id": 139, "title": "Poland", "code": "PL", "code2": "pl", "dial_code": 48, "currency_type": "PLN"},
    {"id": 140, "title": "Portugal", "code": "PT", "code2": "pt", "dial_code": 351, "currency_type": "€"},
    {"id": 141, "title": "Qatar", "code": "QA", "code2": "qa", "dial_code": 974, "currency_type": "QAR"},
    {"id": 142, "title": "Romania", "code": "RO", "code2": "ro", "dial_code": 40, "currency_type": "RON"},
    {"id": 143, "title": "Russia", "code": "RU", "code2": "ru", "dial_code": 7, "currency_type": "₽"},
    {"id": 144, "title": "Rwanda", "code": "RW", "code2": "rw", "dial_code": 252, "currency_type": "RWF"},
    {"id": 145, "title": "Saint Helena", "code": "SH", "code2": "sh", "dial_code": 290, "currency_type": "SHP"},
    {"id": 146, "title": "Saint Kitts and Nevis", "code": "KN", "code2": "kn", "dial_code": 1, "currency_type": "$"},
    {"id": 147, "title": "Saint Lucia", "code": "LC", "code2": "lc", "dial_code": 1, "currency_type": "$"},
    {"id": 148, "title": "Saint Vincent and the Grenadines", "code": "VC", "code2": "vc", "dial_code": 1, "currency_type": "$"},
    {"id": 149, "title": "Samoa", "code": "WS", "code2": "ws", "dial_code": 685, "currency_type": "WST"},
    {"id": 150, "title": "San Marino", "code": "SM", "code2": "sm", "dial_code": 378, "currency_type": "€"},
    {"id": 151, "title": "Sao Tome and Principe", "code": "ST", "code2": "st", "dial_code": 239, "currency_type": "STD"},
    {"id": 152, "title": "Saudi Arabia", "code": "SA", "code2": "sa", "dial_code": 966, "currency_type": "SAR"},
    {"id": 153, "title": "Senegal", "code": "SN", "code2": "sn", "dial_code": 221, "currency_type": "XOF"},
    {"id": 154, "title": "Serbia", "code": "RS", "code2": "rs", "dial_code": 381, "currency_type": "RSD"},
    {"id": 155, "title": "Seychelles", "code": "SC", "code2": "sc", "dial_code": 248, "currency_type": "SCR"},
    {"id": 156, "title": "Sierra Leone", "code": "SL", "code2": "sl", "dial_code": 232, "currency_type": "SLL"},
    {"id": 157, "title": "Singapore", "code": "SG", "code2": "sg", "dial_code": 65, "currency_type": "$"},
    {"id": 158, "title": "Slovakia", "code": "SK", "code2": "sk", "dial_code": 421, "currency_type": "€"},
    {"id": 159, "title": "Slovenia", "code": "SI", "code2": "si", "dial_code": 386, "currency_type": "€"},
    {"id": 160, "title": "Solomon Islands", "code": "SB", "code2": "sb", "dial_code": 677, "currency_type": "SBD"},
    {"id": 161, "title": "Somalia", "code": "SO", "code2": "so", "dial_code": 252, "currency_type": "SOS"},
    {"id": 162, "title": "South Africa", "code": "ZA", "code2": "za", "dial_code": 27, "currency_type": "R"},
    {"id": 163, "title": "South Korea", "code": "KR", "code2": "kr", "dial_code": 82, "currency_type": "₩"},
    {"id": 164, "title": "South Sudan", "code": "SS", "code2": "ss", "dial_code": 211, "currency_type": "SSP"},
    {"id": 165, "title": "Spain", "code": "ES", "code2": "es", "dial_code": 34, "currency_type": "€"},
    {"id": 166, "title": "Sri Lanka", "code": "LK", "code2": "lk", "dial_code": 94, "currency_type": "LKR"},
    {"id": 167, "title": "Sudan", "code": "SD", "code2": "sd", "dial_code": 249, "currency_type": "SDG"},
    {"id": 168, "title": "Suriname", "code": "SR", "code2": "sr", "dial_code": 597, "currency_type": "$"},
    {"id": 169, "title": "Sweden", "code": "SE", "code2": "se", "dial_code": 46, "currency_type": "kr"},
    {"id": 170, "title": "Switzerland", "code": "CH", "code2": "ch", "dial_code": 41, "currency_type": "CHF"},
    {"id": 171, "title": "Syria", "code": "SY", "code2": "sy", "dial_code": 963, "currency_type": "SYP"},
    {"id": 172, "title": "Tajikistan", "code": "TJ", "code2": "tj", "dial_code": 992, "currency_type": "TJS"},
    {"id": 173, "title": "Tanzania", "code": "TZ", "code2": "tz", "dial_code": 255, "currency_type": "TZS"},
    {"id": 174, "title": "Thailand", "code": "TH", "code2": "th", "dial_code": 66, "currency_type": "฿"},
    {"id": 175, "title": "Timor-Leste", "code": "TL", "code2": "tl", "dial_code": 670, "currency_type": "$"},
    {"id": 176, "title": "Togo", "code": "TG", "code2": "tg", "dial_code": 228, "currency_type": "XOF"},
    {"id": 177, "title": "Tonga", "code": "TO", "code2": "to", "dial_code": 676, "currency_type": "TOP"},
    {"id": 178, "title": "Trinidad and Tobago", "code": "TT", "code2": "tt", "dial_code": 1, "currency_type": "$"},
    {"id": 179, "title": "Tunisia", "code": "TN", "code2": "tn", "dial_code": 216, "currency_type": "TND"},
    {"id": 180, "title": "Turkey", "code": "TR", "code2": "tr", "dial_code": 90, "currency_type": "₺"},
    {"id": 181, "title": "Turkmenistan", "code": "TM", "code2": "tm", "dial_code": 993, "currency_type": "TMT"},
    {"id": 182, "title": "Tuvalu", "code": "TV", "code2": "tv", "dial_code": 688, "currency_type": "$"},
    {"id": 183, "title": "Uganda", "code": "UG", "code2": "ug", "dial_code": 256, "currency_type": "UGX"},
    {"id": 184, "title": "Ukraine", "code": "UA", "code2": "ua", "dial_code": 380, "currency_type": "₴"},
    {"id": 185, "title": "United Arab Emirates", "code": "AE", "code2": "ae", "dial_code": 971, "currency_type": "AED"},
    {"id": 186, "title": "United Kingdom", "code": "GB", "code2": "gb", "dial_code": 44, "currency_type": "£"},
    {"id": 187, "title": "United States", "code": "US", "code2": "us", "dial_code": 1, "currency_type": "$"},
    {"id": 188, "title": "Uruguay", "code": "UY", "code2": "uy", "dial_code": 598, "currency_type": "$"},
    {"id": 189, "title": "Uzbekistan", "code": "UZ", "code2": "uz", "dial_code": 998, "currency_type": "UZS"},
    {"id": 190, "title": "Vanuatu", "code": "VU", "code2": "vu", "dial_code": 678, "currency_type": "VUV"},
    {"id": 191, "title": "Vatican City", "code": "VA", "code2": "va", "dial_code": 379, "currency_type": "€"},
    {"id": 192, "title": "Venezuela", "code": "VE", "code2": "ve", "dial_code": 58, "currency_type": "VES"},
    {"id": 193, "title": "Vietnam", "code": "VN", "code2": "vn", "dial_code": 84, "currency_type": "₫"},
    {"id": 194, "title": "Yemen", "code": "YE", "code2": "ye", "dial_code": 967, "currency_type": "YER"},
    {"id": 195, "title": "Zambia", "code": "ZM", "code2": "zm", "dial_code": 260, "currency_type": "ZMW"},
    {"id": 196, "title": "Zimbabwe", "code": "ZW", "code2": "zw", "dial_code": 263, "currency_type": "ZWL"},
]

def seed_countries():
    # First, delete all existing countries
    Countries.objects.all().delete()
    
    # Then create all 195+ countries
    for country_data in COUNTRIES:
        obj = Countries.objects.create(
            id=country_data["id"],
            title=country_data["title"],
            code=country_data["code"],
            code2=country_data["code2"],
            dial_code=country_data["dial_code"],
            image=f"https://flagcdn.com/w40/{country_data['code2']}.png",
            currency_type=country_data["currency_type"],
            shipping_fee=0,
            cod_charge=0,
            is_cod_available=True,
            redeem_point_cash=1,
            is_active=True,
        )
        print(f"Country {country_data['title']} - created with id {obj.id}")

if __name__ == "__main__":
    seed_countries()
    print("All countries seeded successfully!")