# Generated by Django 2.2 on 2020-04-18 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers_management', '0001_initial'),
        ('categories', '0002_auto_20200417_1336'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Affiliate Payment Type',
                'verbose_name_plural': 'Affiliate Payment Type',
                'db_table': 'tbl_affiliate_payment_type',
            },
        ),
        migrations.CreateModel(
            name='Affiliates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_no', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=256)),
                ('locality', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('postal_code', models.CharField(max_length=10)),
                ('payment_details', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Countries')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers_management.Offers')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliate_management.PaymentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affiliate',
                'verbose_name_plural': 'Affiliates',
                'db_table': 'tbl_affiliates',
            },
        ),
    ]
