# Generated by Django 2.2 on 2020-07-18 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20200430_1206'),
        ('affiliate_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliates',
            options={'verbose_name': 'Affiliate', 'verbose_name_plural': '1. Affiliates'},
        ),
        migrations.AlterModelOptions(
            name='paymenttype',
            options={'verbose_name': 'Affiliate Payment Type', 'verbose_name_plural': '2. Affiliate Payment Type'},
        ),
        migrations.AddField(
            model_name='affiliates',
            name='phone_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country_code', to='categories.Countries'),
            preserve_default=False,
        ),
    ]
