# Generated by Django 2.2 on 2020-07-28 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_management', '0002_auto_20200718_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttype',
            options={'verbose_name': 'Payment Type', 'verbose_name_plural': '2. Payment Type'},
        ),
        migrations.RemoveField(
            model_name='affiliates',
            name='locality',
        ),
        migrations.AddField(
            model_name='affiliates',
            name='is_otp_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affiliates',
            name='otp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='affiliates',
            name='otp_expired',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='affiliates',
            name='referral_affiliate',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='affiliates',
            name='referral_code',
            field=models.CharField(default='123456', max_length=120, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affiliates',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers_management.Offers'),
        ),
        migrations.AlterField(
            model_name='affiliates',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
