# Generated by Django 2.2 on 2020-07-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_management', '0003_auto_20200728_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliates',
            name='social_media',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
