# Generated by Django 2.2 on 2020-07-28 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_management', '0004_affiliates_social_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliates',
            name='referral_affiliate',
        ),
        migrations.CreateModel(
            name='AffiliatesReferral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliate_management.Affiliates')),
                ('referred_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='affiliate_management.Affiliates')),
            ],
            options={
                'verbose_name': 'Affiliate Referral',
                'verbose_name_plural': 'Affiliates Referrals',
                'db_table': 'tbl_affiliates_referral',
                'unique_together': {('referred_by', 'referral')},
            },
        ),
    ]
