# Generated by Django 2.2 on 2020-07-29 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_management', '0005_auto_20200728_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pre_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_credit', models.BooleanField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='affiliate_management.Affiliates')),
            ],
            options={
                'db_table': 'tbl_wallet_history',
            },
        ),
    ]
