# Generated by Django 2.2 on 2020-07-30 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_management', '0006_wallethistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallethistory',
            name='pre_amount',
        ),
        migrations.AlterField(
            model_name='affiliates',
            name='offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_offer', to='offers_management.Offers'),
        ),
    ]
