# Generated by Django 2.2 on 2020-08-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_management', '0007_auto_20200730_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliates',
            name='social_media',
            field=models.CharField(blank=True, help_text='Eg: Fb link, Insta, etc', max_length=256, null=True),
        ),
    ]
