# Generated by Django 2.2 on 2020-08-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_management', '0008_auto_20200802_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliates',
            name='wallet_amount',
            field=models.FloatField(default=0),
        ),
    ]
