# Generated by Django 2.2 on 2020-08-02 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_auto_20200731_1348'),
        ('affiliate_management', '0009_affiliates_wallet_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallethistory',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.Countries'),
        ),
    ]
