# Generated by Django 2.2 on 2020-08-03 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_management', '0010_wallethistory_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliates',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='affiliates',
            name='total_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='affiliatesreferral',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_user', to='affiliate_management.Affiliates'),
        ),
        migrations.AlterField(
            model_name='wallethistory',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
