"""
Django settings for space_and_beauty project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import sys
# --- Compatibility shim for Python 3.14 where cgi.parse_header was removed ---
try:
    import cgi as _std_cgi
    if not hasattr(_std_cgi, "parse_header"):
        # Load our local shim (cgi.py placed in the project root)
        try:
            import importlib.util
            import pathlib
            shim_path = pathlib.Path(__file__).parent.parent / "cgi.py"
            spec = importlib.util.spec_from_file_location("cgi", shim_path)
            shim_module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(shim_module)
            sys.modules["cgi"] = shim_module
        except Exception as e:
            # Fallback: define a minimal parse_header inline
            def parse_header(line):
                parts = line.split(";") if line else []
                ctype = parts[0].strip() if parts else ""
                params = {}
                for param in parts[1:]:
                    if "=" in param:
                        k, v = param.strip().split("=", 1)
                        if v.startswith('"') and v.endswith('"'):
                            v = v[1:-1]
                        params[k] = v
                    else:
                        params[param.strip()] = ""
                return ctype, params
            _std_cgi.parse_header = parse_header
            sys.modules["cgi"] = _std_cgi
except Exception:
    pass

# --- Compatibility shim for Python 3.14 where pkgutil.find_loader was removed ---
# django_filters 2.2.0 uses pkgutil.find_loader() which was removed in Python 3.12+.
# We restore a minimal implementation so the package keeps working.
try:
    import pkgutil as _pkgutil
    if not hasattr(_pkgutil, "find_loader"):
        import importlib.util as _importlib_util

        def _find_loader(fullname):
            try:
                spec = _importlib_util.find_spec(fullname)
                return spec.loader if spec else None
            except (ImportError, AttributeError, ValueError):
                return None

        _pkgutil.find_loader = _find_loader
except Exception:
    pass

# --- Compatibility shim for Django 2.2 on Python 3.14 template rendering ---
try:
    from copy import copy as _copy
    from django.template.context import BaseContext as _BaseContext

    def _base_context_copy(self):
        duplicate = object.__new__(self.__class__)
        duplicate.dicts = self.dicts[:]
        for key, value in self.__dict__.items():
            if key != "dicts":
                setattr(duplicate, key, _copy(value))
        return duplicate

    _BaseContext.__copy__ = _base_context_copy
except Exception:
    pass

import pymysql
pymysql.install_as_MySQLdb()
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PROJECT_ROOT = os.path.realpath(os.path.dirname(__file__))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ezwxg3@36f@=z#hiwqf^=l$63vdi5v%onwxux&!ek)ldfuqk5('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'categories.apps.CategoriesConfig',
    'django.contrib.admin.apps.AdminConfig',
    'cart_management.apps.CartManagementConfig',
    'authentication.apps.AuthenticationConfig',
    'product_management.apps.ProductManagementConfig',
    'orders_management.apps.OrdersManagementConfig',
    'accounts.apps.AccountsConfig',
    'offers_management.apps.OffersManagementConfig',
    'affiliate_management.apps.AffiliateManagementConfig',
    'blog_management.apps.BlogManagementConfig',
    'tokens_management.apps.TokensManagementConfig',
    'others.apps.OthersConfig',
    'administration.apps.AdministrationConfig',

    'hero',
    'space_and_beauty.apps.SuitConfig',

    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django.contrib.humanize",

    'corsheaders',
    'rest_framework',
    'django_summernote',
    'django_admin_listfilter_dropdown',
    'annoying',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # CsrfViewMiddleware is REQUIRED for Django admin login forms.
    # DRF API views are already decorated with @csrf_exempt internally,
    # so this does NOT affect REST API calls from Next.js.
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'space_and_beauty.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'space_and_beauty.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'authentication.authentication.TokenAuthentication',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/minute',
        'user': '60/minute'
    },
    'SEARCH_PARAM': 'q',
}

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = False

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/


STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(PROJECT_ROOT, 'static/'),
)

MEDIA_ROOT = os.path.join(PROJECT_ROOT, 'media')

MEDIA_URL = '/media/'

# CORS SETUP

CORS_ORIGIN_WHITELIST = (
    'null',
)

CORS_ORIGIN_REGEX_WHITELIST = r"^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$"

CORS_ALLOW_METHODS = (
    'POST',
    'GET',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
)

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_HEADERS = (
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-guest-session-id',
)

USER = {
    'DOMAIN': 'www.tharagar.com',
    'SITE_NAME': 'Tharagar',
    'PASSWORD_RESET_CONFIRM_URL': 'reset-password?uid={uid}&token={token}',
    'ACTIVATION_URL': 'email-verification?uid={uid}&token={token}',
    'SEND_ACTIVATION_EMAIL': True,
}

# CSRF Trusted Origins — required for Django admin cross-origin POST forms
# (Django 4.0+ requires this; harmless on older versions)
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    # Add your production frontend URL here:
    # 'https://www.tharagar.com',
]
