# Generated by Django 2.2 on 2020-04-17 14:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_management', '0002_auto_20200406_1330'),
        ('accounts', '0001_initial'),
        ('categories', '0002_auto_20200417_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Order Status',
                'verbose_name_plural': 'Order Status',
                'db_table': 'tbl_order_status_master',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders_management.OrderStatusMaster')),
            ],
            options={
                'verbose_name': 'Order Status',
                'verbose_name_plural': 'Order Status',
                'db_table': 'tbl_order_status',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_client_id', models.CharField(blank=True, editable=False, max_length=40, unique=True, verbose_name='Tracking ID')),
                ('payment_type', models.CharField(choices=[('Online', 'Online'), ('COD', 'Cash On Delivery')], max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('coupon_amount', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('pay_amount', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('shipping_charge', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('cod_charge', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('other_charge', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Address')),
                ('payment_gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.PaymentGateWay')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders_management.OrderStatus')),
            ],
            options={
                'verbose_name': 'Orders',
                'verbose_name_plural': 'Orders',
                'db_table': 'tbl_orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('shipping_charge', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('cod_charge', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('other_charge', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.Countries')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders_management.Orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.Products')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'tbl_order_items',
            },
        ),
    ]
