# Generated by Django 2.2 on 2020-07-18 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelPlaced',
            fields=[
            ],
            options={
                'verbose_name': 'Canceled Order',
                'verbose_name_plural': '1. Canceled Order',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders_management.orders',),
        ),
        migrations.CreateModel(
            name='InfluencerPlaced',
            fields=[
            ],
            options={
                'verbose_name': 'Influencer Order',
                'verbose_name_plural': '2. Influencer Placed',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders_management.orders',),
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
            ],
            options={
                'verbose_name': 'Order Placed',
                'verbose_name_plural': '1. Order Placed',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders_management.orders',),
        ),
    ]
