# Generated by Django 2.2 on 2020-07-18 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0002_cancelplaced_influencerplaced_orderplaced'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancelplaced',
            options={'verbose_name': 'Canceled Order', 'verbose_name_plural': '3. Canceled Order'},
        ),
    ]
