# Generated by Django 2.2 on 2020-07-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0004_auto_20200720_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='alt_phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
