# Generated by Django 2.2 on 2020-07-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0005_orders_alt_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='alt_dial_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
