# Generated by Django 2.2 on 2020-07-25 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0006_orders_alt_dial_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders_management.Orders'),
        ),
    ]
