# Generated by Django 2.2 on 2020-07-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0007_auto_20200725_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
