# Generated by Django 2.2 on 2020-07-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0008_orders_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_wallet',
            field=models.BooleanField(default=False),
        ),
    ]
