# Generated by Django 2.2 on 2020-07-31 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0009_orders_is_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='cod_charge',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='other_charge',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='shipping_charge',
        ),
    ]
