# Generated by Django 2.2 on 2020-08-02 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_management', '0008_auto_20200802_1554'),
        ('product_management', '0008_auto_20200802_1554'),
        ('orders_management', '0010_auto_20200731_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.FloatField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('affiliates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliate_management.Affiliates')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.Products')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders_management.OrderStatus')),
            ],
            options={
                'verbose_name': 'Influencer Order',
                'verbose_name_plural': '2. Influencer Order',
                'db_table': 'tbl_influencer_order',
            },
        ),
        migrations.DeleteModel(
            name='InfluencerPlaced',
        ),
    ]
