# Generated by Django 2.2 on 2020-08-02 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0011_auto_20200802_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencerorder',
            name='unit_price',
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='product_management.Products'),
        ),
    ]
