# Generated by Django 2.2 on 2020-08-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0012_auto_20200802_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='unit_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='cod_charge',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='coupon_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='other_charge',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pay_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipping_charge',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
