# Generated by Django 2.2 on 2020-10-24 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0013_auto_20200803_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivered',
            fields=[
            ],
            options={
                'verbose_name': 'Delivered',
                'verbose_name_plural': '5. Delivered',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders_management.orders',),
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
            ],
            options={
                'verbose_name': ' Shipped',
                'verbose_name_plural': '4. Shipped',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders_management.orders',),
        ),
        migrations.CreateModel(
            name='ReadyForDispatch',
            fields=[
            ],
            options={
                'verbose_name': 'Ready To Ship',
                'verbose_name_plural': '3. Ready To Ship',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders_management.orders',),
        ),
        migrations.CreateModel(
            name='ReturnedOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Returned Order',
                'verbose_name_plural': '7. Returned Order',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders_management.orders',),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': '1. Transaction',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders_management.orders',),
        ),
        migrations.AlterModelOptions(
            name='cancelplaced',
            options={'verbose_name': 'Canceled Order', 'verbose_name_plural': '6. Canceled Order'},
        ),
        migrations.AlterModelOptions(
            name='influencerorder',
            options={'verbose_name': 'Influencer Order', 'verbose_name_plural': 'Influencer Order'},
        ),
        migrations.AlterModelOptions(
            name='orderplaced',
            options={'verbose_name': 'Order Placed', 'verbose_name_plural': '2. Order Placed'},
        ),
        migrations.AddField(
            model_name='orders',
            name='awb_code',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='track_url',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_offer', to='offers_management.Offers'),
        ),
    ]
