# Generated by Django 2.2 on 2021-01-20 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0014_auto_20201024_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllOrder',
            fields=[
            ],
            options={
                'verbose_name': 'All Order',
                'verbose_name_plural': '8. All Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders_management.orders',),
        ),
    ]
