# Generated by Django 2.2 on 2021-02-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0015_allorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='offer_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='offer_title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
