# Generated by Django 2.2 on 2021-10-15 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0016_auto_20210215_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivered',
            options={'verbose_name': 'Delivered'},
        ),
    ]
