# Generated by Django 2.2 on 2021-10-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0017_auto_20211015_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='gst',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='total_gst',
            field=models.FloatField(default=0),
        ),
    ]
