# Generated by Django 2.2 on 2021-10-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0018_auto_20211015_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='color',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
