# Generated by Django 2.2 on 2021-12-01 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0011_categoriesimage'),
        ('orders_management', '0019_orderitems_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='pay_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_mode', to='categories.PaymentGateWay', verbose_name='Pay Mode'),
        ),
    ]
