# Generated by Django 2.2 on 2022-02-15 18:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0011_categoriesimage'),
        ('product_management', '0011_products_weight'),
        ('orders_management', '0020_orders_pay_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_amount_refunded',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='orders',
            name='refund_amount',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='OrderItemsCancelled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('offer_title', models.CharField(blank=True, max_length=120, null=True)),
                ('offer_amount', models.FloatField(default=0.0)),
                ('unit_price', models.FloatField(default=0)),
                ('gst', models.FloatField(default=0)),
                ('color', models.CharField(blank=True, max_length=120, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.Countries')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items_cancelled', to='orders_management.Orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.Products')),
            ],
            options={
                'db_table': 'tbl_order_items_cancellation',
            },
        ),
    ]
