# Generated by Django 2.2 on 2020-04-06 13:16

from django.db import migrations, models
import django.db.models.deletion
import product_management.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=15, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField()),
                ('thumbnail_image', models.ImageField(upload_to=product_management.validators.upload_to_title_images)),
                ('support_number', models.CharField(max_length=15)),
                ('is_barter', models.BooleanField()),
                ('is_pre_order', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.SubCategories')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'tbl_products',
            },
        ),
        migrations.CreateModel(
            name='ProductVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('video', models.ImageField(upload_to=product_management.validators.upload_to_title_images)),
                ('content_type', models.CharField(max_length=120)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.Products')),
            ],
            options={
                'verbose_name': 'Product Video',
                'verbose_name_plural': 'Product Videos',
                'db_table': 'tbl_product_videos',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('images', models.ImageField(upload_to=product_management.validators.upload_to_title_images)),
                ('content_type', models.CharField(max_length=120)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.Products')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'db_table': 'tbl_product_image',
            },
        ),
        migrations.CreateModel(
            name='ProductContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(choices=[('Return Policy', 'Return Policy'), ('Terms and Conditions', 'Terms and Conditions'), ('Damage and exchange', 'Damage and exchange'), ('Note', 'Note'), ('Delivery Details', 'Delivery Details')], max_length=256)),
                ('content', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.Products')),
            ],
            options={
                'verbose_name': 'Product Content',
                'verbose_name_plural': 'Product Content',
                'db_table': 'tbl_product_content',
                'unique_together': {('product', 'heading')},
            },
        ),
        migrations.CreateModel(
            name='ProductAvailableCountries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.PositiveIntegerField()),
                ('selling_price', models.PositiveIntegerField()),
                ('is_cod_avail', models.BooleanField()),
                ('cod_charge', models.PositiveIntegerField(default=0.0)),
                ('delivery_charge', models.PositiveIntegerField(default=0.0)),
                ('promotion_text', models.CharField(blank=True, max_length=256, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Countries')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.Products')),
            ],
            options={
                'verbose_name': 'Product Available Country',
                'verbose_name_plural': 'Product Available Countries',
                'db_table': 'tbl_product_available_countries',
                'unique_together': {('product', 'country')},
            },
        ),
    ]
