# Generated by Django 2.2 on 2020-04-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='images',
            new_name='image',
        ),
    ]
