# Generated by Django 2.2 on 2020-04-21 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_auto_20200406_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productavailablecountries',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_country', to='product_management.Products'),
        ),
        migrations.AlterField(
            model_name='productcontent',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_content', to='product_management.Products'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='product_management.Products'),
        ),
        migrations.AlterField(
            model_name='productvideos',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_videos', to='product_management.Products'),
        ),
    ]
