# Generated by Django 2.2 on 2020-07-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_auto_20200421_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
