# Generated by Django 2.2 on 2020-07-18 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0004_products_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-ordering'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
