# Generated by Django 2.2 on 2020-07-29 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0005_auto_20200718_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='affiliate_percentage',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(80)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='is_barter_order_count',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='is_stock',
            field=models.BooleanField(default=True),
        ),
    ]
