# Generated by Django 2.2 on 2020-07-31 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0006_auto_20200729_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productavailablecountries',
            name='cod_charge',
        ),
        migrations.RemoveField(
            model_name='productavailablecountries',
            name='delivery_charge',
        ),
        migrations.RemoveField(
            model_name='productavailablecountries',
            name='is_cod_avail',
        ),
    ]
