# Generated by Django 2.2 on 2020-08-02 15:54

from django.db import migrations, models
import product_management.validators


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0007_auto_20200731_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvideos',
            name='video',
            field=models.FileField(upload_to=product_management.validators.upload_to_title_images),
        ),
    ]
