# Generated by Django 2.2 on 2021-01-29 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_auto_20210129_2348'),
        ('product_management', '0008_auto_20200802_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentNeededProducts',
            fields=[
            ],
            options={
                'verbose_name': 'ContentNeeded Products',
                'verbose_name_plural': '2. ContentNeeded Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('product_management.products',),
        ),
        migrations.CreateModel(
            name='ContentUpdatedProducts',
            fields=[
            ],
            options={
                'verbose_name': 'Content Updated Products',
                'verbose_name_plural': '3. Content Updated Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('product_management.products',),
        ),
        migrations.CreateModel(
            name='PublishedProducts',
            fields=[
            ],
            options={
                'verbose_name': 'Published Publish',
                'verbose_name_plural': '5. Published Publish',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('product_management.products',),
        ),
        migrations.CreateModel(
            name='ReadyPublishProducts',
            fields=[
            ],
            options={
                'verbose_name': 'Ready to Publish',
                'verbose_name_plural': '4. Ready to Publish',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('product_management.products',),
        ),
        migrations.CreateModel(
            name='UploadedProducts',
            fields=[
            ],
            options={
                'verbose_name': 'Uploaded Products',
                'verbose_name_plural': '1. Uploaded Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('product_management.products',),
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='content_type',
        ),
        migrations.AddField(
            model_name='products',
            name='bt_code',
            field=models.CharField(default='00001', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='financial_year',
            field=models.CharField(default=2021, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='price_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.PricingCategories'),
        ),
        migrations.AddField(
            model_name='products',
            name='short_descriptions',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.IntegerField(choices=[(1, 'Uploaded'), (2, 'Need to Content'), (3, 'Content Updated'), (4, 'Approved'), (5, 'Published')], default=1),
        ),
        migrations.AddField(
            model_name='products',
            name='stock_qty',
            field=models.PositiveIntegerField(default=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcontent',
            name='heading',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(upload_to='product/product-image/'),
        ),
    ]
