# Generated by Django 2.2 on 2021-04-02 18:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_auto_20210402_1805'),
        ('product_management', '0009_auto_20210129_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProductsProducts',
            fields=[
            ],
            options={
                'verbose_name': 'All Products',
                'verbose_name_plural': ' All Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('product_management.products',),
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='categories.Categories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_designs', to='categories.ProductDesign'),
        ),
        migrations.AddField(
            model_name='products',
            name='design_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_designs_type', to='categories.DesignType'),
        ),
        migrations.AddField(
            model_name='products',
            name='tags',
            field=models.ManyToManyField(blank=True, to='categories.ProductTags'),
        ),
        migrations.AlterField(
            model_name='products',
            name='affiliate_percentage',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(80)]),
        ),
        migrations.AlterField(
            model_name='products',
            name='bt_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='financial_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_barter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_barter_order_count',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_pre_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='sku',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories_product', to='categories.SubCategories'),
        ),
    ]
