# Generated by Django 2.2 on 2021-11-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0010_auto_20210402_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='weight',
            field=models.FloatField(default=0.8),
            preserve_default=False,
        ),
    ]
