# Generated by Django 2.2 on 2026-07-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0011_products_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_hero_featured',
            field=models.BooleanField(default=False, help_text='Show this product in frontend hero floating cards'),
        ),
    ]
