# Generated by Django 2.2 on 2026-07-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0012_products_is_hero_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='is_hero_featured',
        ),
    ]
