# Generated by Django 2.2 on 2026-08-05 12:32

from django.db import migrations, models
import product_management.validators


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0013_remove_products_is_hero_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='hover_image',
            field=models.ImageField(blank=True, null=True, upload_to=product_management.validators.upload_to_title_images),
        ),
    ]
