# Generated by Django 2.2 on 2020-04-17 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0002_auto_20200417_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Delivery Person name', max_length=256)),
                ('street_address_1', models.CharField(max_length=256)),
                ('street_address_2', models.CharField(blank=True, max_length=256)),
                ('city', models.CharField(blank=True, max_length=256)),
                ('landmark', models.CharField(blank=True, max_length=256)),
                ('phone', models.CharField(max_length=15)),
                ('address_type', models.CharField(choices=[('Home', 'Home'), ('Work', 'Work')], max_length=20, verbose_name='Address Type')),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Countries')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Address',
                'db_table': 'tbl_user_address',
            },
        ),
    ]
