# Generated by Django 2.2 on 2020-04-29 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200420_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(help_text='Delivery Person name', max_length=256),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userpointshistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_points_history', to='accounts.UserProfile'),
        ),
    ]
