# Generated by Django 2.2 on 2020-07-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200429_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='dial_code',
            field=models.PositiveIntegerField(default=91),
            preserve_default=False,
        ),
    ]
