# Generated by Django 2.2 on 2020-07-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_address_dial_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default='Tamilnadu', max_length=120),
            preserve_default=False,
        ),
    ]
