# Generated by Django 2.2 on 2020-07-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_points',
            field=models.IntegerField(default=0),
        ),
    ]
