# Generated by Django 2.2 on 2020-07-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200720_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='dial_code',
        ),
        migrations.RemoveField(
            model_name='address',
            name='name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='phone',
        ),
    ]
