# Generated by Django 2.2 on 2020-07-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_userprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='used_points',
            field=models.IntegerField(default=0),
        ),
    ]
