# Generated by Django 2.2 on 2020-07-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='locality',
            field=models.CharField(default='Sample Locality', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='landmark',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_points',
            field=models.IntegerField(default=0, verbose_name='Total Earned Points'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='used_points',
            field=models.IntegerField(default=0, verbose_name='Total User Points'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_points',
            field=models.IntegerField(default=0, verbose_name='Available Points'),
        ),
    ]
