# Generated by Django 2.2 on 2020-08-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200731_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpointshistory',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
