# Generated by Django 2.2 on 2020-08-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userpointshistory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='total_points',
            field=models.IntegerField(verbose_name='Total Earned Points'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='used_points',
            field=models.IntegerField(verbose_name='Total User Points'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_points',
            field=models.IntegerField(verbose_name='Available Points'),
        ),
    ]
