# Generated by Django 2.2 on 2020-08-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200803_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='total_points',
            field=models.IntegerField(default=0, verbose_name='Total Earned Points'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='used_points',
            field=models.IntegerField(default=0, verbose_name='Total User Points'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_points',
            field=models.IntegerField(default=0, verbose_name='Available Points'),
        ),
    ]
