# Generated by Django 2.2 on 2020-04-19 14:10

import blog_management.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=120, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('profile_pic', models.ImageField(upload_to='blog-image/author')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'db_table': 'tbl_author',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Blog Tag',
                'verbose_name_plural': 'Blog Tags',
                'db_table': 'tbl_blog_tags',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField()),
                ('short_description', models.CharField(max_length=254)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=blog_management.models.upload_to_photos)),
                ('is_active', models.BooleanField(default=False)),
                ('meta_keyword', models.CharField(blank=True, max_length=256, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=600, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_management.Authors')),
                ('tag', models.ManyToManyField(blank=True, to='blog_management.Tags')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog',
                'db_table': 'tbl_blog',
            },
        ),
    ]
