# Generated by Django 2.2 on 2020-04-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateWay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateway',
                'db_table': 'tbl_payment_gateway',
            },
        ),
        migrations.AddField(
            model_name='countries',
            name='redeem_point_cash',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countries',
            name='shipping_free',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Shipping charge free base amount', max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countries',
            name='available_payment_gateway',
            field=models.ManyToManyField(blank=True, to='categories.PaymentGateWay'),
        ),
    ]
