# Generated by Django 2.2 on 2020-04-23 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20200417_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='currency_type',
            field=models.CharField(default='$', max_length=5, verbose_name='Country Symbol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countries',
            name='image',
            field=models.ImageField(default='country_image.png', upload_to='country_image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='categories.Categories'),
        ),
    ]
