# Generated by Django 2.2 on 2020-04-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20200423_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='redeem_point_cash',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='countries',
            name='shipping_free',
            field=models.FloatField(help_text='Shipping charge free base amount'),
        ),
    ]
