# Generated by Django 2.2 on 2020-07-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20200430_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countries',
            old_name='shipping_free',
            new_name='shipping_fee',
        ),
        migrations.AlterField(
            model_name='countries',
            name='currency_type',
            field=models.CharField(max_length=5, verbose_name='Currency Symbol'),
        ),
    ]
