# Generated by Django 2.2 on 2020-07-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20200718_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='code2',
            field=models.CharField(default='IN', max_length=2),
            preserve_default=False,
        ),
    ]
