# Generated by Django 2.2 on 2020-07-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_countries_code2'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='cod_charge',
            field=models.FloatField(default=0.0, help_text='Shipping charge free base amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countries',
            name='is_cod_available',
            field=models.BooleanField(default=True),
        ),
    ]
