# Generated by Django 2.2 on 2021-01-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_auto_20200731_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('from_start', models.PositiveIntegerField(verbose_name='Range From Price')),
                ('to_end', models.PositiveIntegerField(verbose_name='Range To Price')),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'verbose_name': 'Pricing Categories',
                'verbose_name_plural': 'Pricing Categories',
                'db_table': 'tbl_pricing_categories',
            },
        ),
        migrations.AddField(
            model_name='categories',
            name='code',
            field=models.CharField(default='F', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategories',
            name='code',
            field=models.CharField(default='E', max_length=3),
            preserve_default=False,
        ),
    ]
