# Generated by Django 2.2 on 2021-04-02 18:03

import categories.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_auto_20210129_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=categories.validators.upload_to_title_images)),
            ],
            options={
                'verbose_name': 'Design Type',
                'verbose_name_plural': 'Design Type',
                'db_table': 'tbl_design_type',
            },
        ),
        migrations.CreateModel(
            name='ProductDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Product Design',
                'verbose_name_plural': 'Product Design',
                'db_table': 'tbl_product_design',
            },
        ),
        migrations.CreateModel(
            name='SuperCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('title', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('short_description', models.CharField(blank=True, max_length=256, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=categories.validators.upload_to_title_images)),
            ],
            options={
                'verbose_name': 'Super Category',
                'verbose_name_plural': 'Super Categories',
                'db_table': 'tbl_super_categories',
            },
        ),
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='title',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterUniqueTogether(
            name='subcategories',
            unique_together={('category', 'title')},
        ),
        migrations.CreateModel(
            name='ProductTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to=categories.validators.upload_to_title_images)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='categories.Categories')),
            ],
            options={
                'verbose_name': 'Product & Category Tags',
                'verbose_name_plural': 'Product & Category Tags',
                'db_table': 'tbl_category_product_tags',
            },
        ),
    ]
