# Generated by Django 2.2 on 2021-04-02 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_auto_20210402_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='super_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='categories.SuperCategories'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='categories',
            unique_together={('super_category', 'title')},
        ),
    ]
