# Generated by Django 2.2 on 2021-10-15 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_auto_20210402_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_images', to='categories.Categories')),
            ],
            options={
                'db_table': 'tbl_categories_image',
            },
        ),
    ]
