from django.db import migrations


# Extended list of countries with flags and currencies
COUNTRIES = [
    {
        "id": 1,
        "title": "India",
        "code": "INR",
        "code2": "in",
        "dial_code": 91,
        "image": "country_image/india.png",
        "currency_type": "₹",
        "shipping_fee": 0,
        "cod_charge": 0,
        "is_cod_available": True,
        "redeem_point_cash": 1,
        "is_active": True,
    },
    {
        "id": 2,
        "title": "United States",
        "code": "USD",
        "code2": "us",
        "dial_code": 1,
        "image": "country_image/usa_q1Uh2UI.jpg",
        "currency_type": "$",
        "shipping_fee": 0,
        "cod_charge": 0,
        "is_cod_available": True,
        "redeem_point_cash": 1,
        "is_active": True,
    },
    {
        "id": 3,
        "title": "United Kingdom",
        "code": "GBP",
        "code2": "gb",
        "dial_code": 44,
        "image": "country_image/gb_rEWJGw6.png",
        "currency_type": "£",
        "shipping_fee": 0,
        "cod_charge": 0,
        "is_cod_available": True,
        "redeem_point_cash": 1,
        "is_active": True,
    },
    {
        "id": 4,
        "title": "Europe",
        "code": "EUR",
        "code2": "eu",
        "dial_code": 49,
        "image": "country_image/220px-Flag_of_Germany.svg.png",
        "currency_type": "€",
        "shipping_fee": 0,
        "cod_charge": 0,
        "is_cod_available": True,
        "redeem_point_cash": 1,
        "is_active": True,
    },
    {
        "id": 5,
        "title": "Australia",
        "code": "AUD",
        "code2": "au",
        "dial_code": 61,
        "image": "country_image/flag-400_KUN20FB.png",
        "currency_type": "$",
        "shipping_fee": 0,
        "cod_charge": 0,
        "is_cod_available": True,
        "redeem_point_cash": 1,
        "is_active": True,
    },
    {
        "id": 6,
        "title": "Singapore",
        "code": "SGD",
        "code2": "sg",
        "dial_code": 65,
        "image": "country_image/1200px-Flag_of_Singapore.svg.png",
        "currency_type": "$",
        "shipping_fee": 0,
        "cod_charge": 0,
        "is_cod_available": True,
        "redeem_point_cash": 1,
        "is_active": True,
    },
    {
        "id": 7,
        "title": "United Arab Emirates",
        "code": "AED",
        "code2": "ae",
        "dial_code": 971,
        "image": "country_image/1024px-Flag_of_the_United_Arab_Emirates.svg.png",
        "currency_type": "AED",
        "shipping_fee": 0,
        "cod_charge": 0,
        "is_cod_available": True,
        "redeem_point_cash": 1,
        "is_active": True,
    },
    {
        "id": 8,
        "title": "Canada",
        "code": "CAD",
        "code2": "ca",
        "dial_code": 1,
        "image": "country_image/1200px-Flag_of_Canada_Pantone.svg.png",
        "currency_type": "C$",
        "shipping_fee": 0,
        "cod_charge": 0,
        "is_cod_available": True,
        "redeem_point_cash": 1,
        "is_active": True,
    },
    {
        "id": 9,
        "title": "Japan",
        "code": "JPY",
        "code2": "jp",
        "dial_code": 81,
        "image": "country_image/255px-Flag_of_Italy.svg.png",
        "currency_type": "¥",
        "shipping_fee": 0,
        "cod_charge": 0,
        "is_cod_available": True,
        "redeem_point_cash": 1,
        "is_active": True,
    },
    {
        "id": 10,
        "title": "China",
        "code": "CNY",
        "code2": "cn",
        "dial_code": 86,
        "image": "country_image/1200px-Flag_of_Spain.svg.png",
        "currency_type": "¥",
        "shipping_fee": 0,
        "cod_charge": 0,
        "is_cod_available": True,
        "redeem_point_cash": 1,
        "is_active": True,
    },
    {
        "id": 11,
        "title": "South Korea",
        "code": "KRW",
        "code2": "kr",
        "dial_code": 82,
        "image": "country_image/220px-Flag_of_Germany.svg.png",
        "currency_type": "₩",
        "shipping_fee": 0,
        "cod_charge": 0,
        "is_cod_available": True,
        "redeem_point_cash": 1,
        "is_active": True,
    },
    {
        "id": 12,
        "title": "Mexico",
        "code": "MXN",
        "code2": "mx",
        "dial_code": 52,
        "image": "country_image/220px-Flag_of_Germany.svg.png",
        "currency_type": "$",
        "shipping_fee": 0,
        "cod_charge": 0,
        "is_cod_available": True,
        "redeem_point_cash": 1,
        "is_active": True,
    },
    {
        "id": 13,
        "title": "Brazil",
        "code": "BRL",
        "code2": "br",
        "dial_code": 55,
        "image": "country_image/220px-Flag_of_Germany.svg.png",
        "currency_type": "R$",
        "shipping_fee": 0,
        "cod_charge": 0,
        "is_cod_available": True,
        "redeem_point_cash": 1,
        "is_active": True,
    },
    {
        "id": 14,
        "title": "Argentina",
        "code": "ARG",
        "code2": "ar",
        "dial_code": 54,
        "image": "country_image/220px-Flag_of_Germany.svg.png",
        "currency_type": "$",
        "shipping_fee": 0,
        "cod_charge": 0,
        "is_cod_available": True,
        "redeem_point_cash": 1,
        "is_active": True,
    },
    {
        "id": 15,
        "title": "Switzerland",
        "code": "CHF",
        "code2": "ch",
        "dial_code": 41,
        "image": "country_image/220px-Flag_of_Germany.svg.png",
        "currency_type": "CHF",
        "shipping_fee": 0,
        "cod_charge": 0,
        "is_cod_available": True,
        "redeem_point_cash": 1,
        "is_active": True,
    },
    {
        "id": 16,
        "title": "Sweden",
        "code": "SEK",
        "code2": "se",
        "dial_code": 46,
        "image": "country_image/220px-Flag_of_Germany.svg.png",
        "currency_type": "kr",
        "shipping_fee": 0,
        "cod_charge": 0,
        "is_cod_available": True,
        "redeem_point_cash": 1,
        "is_active": True,
    },
    {
        "id": 17,
        "title": "New Zealand",
        "code": "NZD",
        "code2": "nz",
        "dial_code": 64,
        "image": "country_image/220px-Flag_of_Germany.svg.png",
        "currency_type": "$",
        "shipping_fee": 0,
        "cod_charge": 0,
        "is_cod_available": True,
        "redeem_point_cash": 1,
        "is_active": True,
    },
    {
        "id": 18,
        "title": "South Africa",
        "code": "ZAR",
        "code2": "za",
        "dial_code": 27,
        "image": "country_image/220px-Flag_of_Germany.svg.png",
        "currency_type": "R",
        "shipping_fee": 0,
        "cod_charge": 0,
        "is_cod_available": True,
        "redeem_point_cash": 1,
        "is_active": True,
    },
    {
        "id": 19,
        "title": "Russia",
        "code": "RUB",
        "code2": "ru",
        "dial_code": 7,
        "image": "country_image/220px-Flag_of_Germany.svg.png",
        "currency_type": "₽",
        "shipping_fee": 0,
        "cod_charge": 0,
        "is_cod_available": True,
        "redeem_point_cash": 1,
        "is_active": True,
    },
    {
        "id": 20,
        "title": "Thailand",
        "code": "THB",
        "code2": "th",
        "dial_code": 66,
        "image": "country_image/Flag-France.jpg",
        "currency_type": "฿",
        "shipping_fee": 0,
        "cod_charge": 0,
        "is_cod_available": True,
        "redeem_point_cash": 1,
        "is_active": True,
    },
]


def seed_countries(apps, schema_editor):
    Countries = apps.get_model("categories", "Countries")

    for country in COUNTRIES:
        country_id = country["id"]
        defaults = {key: value for key, value in country.items() if key != "id"}

        obj = Countries.objects.filter(code=country["code"]).first()
        if obj:
            for key, value in defaults.items():
                setattr(obj, key, value)
            obj.save()
        else:
            Countries.objects.create(id=country_id, **defaults)


def remove_seeded_countries(apps, schema_editor):
    Countries = apps.get_model("categories", "Countries")
    Countries.objects.filter(code__in=[country["code"] for country in COUNTRIES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0011_categoriesimage"),
    ]

    operations = [
        migrations.RunPython(seed_countries, remove_seeded_countries),
    ]