# Generated by Django 2.2 on 2026-07-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0012_seed_countries'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero Banner'), ('product_grid', 'Product Grid'), ('promotional_banner', 'Promotional Banner'), ('cute_collection', 'Cute Collection'), ('customers_top_choice', 'Customers Top Choice'), ('cute_collection_cards', 'Cute Collection Cards'), ('dream_box_collections', 'Dream Box Collections'), ('testimonials', 'Testimonials'), ('upgrade_essentials', 'Upgrade Essentials')], max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('background_color', models.CharField(blank=True, default='', max_length=50)),
                ('link_url', models.CharField(blank=True, default='', max_length=500)),
                ('link_text', models.CharField(blank=True, default='Shop Now', max_length=100)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Section',
                'verbose_name_plural': 'Homepage Sections',
                'db_table': 'tbl_homepage_sections',
                'ordering': ['ordering'],
            },
        ),
    ]
