# Generated by Django 2.2 on 2026-09-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0013_homepagesection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero Banner'), ('product_grid', 'Product Grid'), ('promotional_banner', 'Promotional Banner'), ('cute_collection', 'Cute Collection'), ('customers_top_choice', 'Customers Top Choice'), ('cute_collection_cards', 'Cute Collection Cards'), ('dream_box_collections', 'Dream Box Collections'), ('testimonials', 'Testimonials'), ('upgrade_essentials', 'Upgrade Essentials'), ('bestseller', 'Bestseller')], max_length=50),
        ),
    ]