# Generated by Django 2.2 on 2026-07-10 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0013_homepagesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSectionProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage_products/')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('link_url', models.CharField(blank=True, default='', max_length=500)),
                ('link_text', models.CharField(blank=True, default='Buy Now', max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('badge', models.CharField(blank=True, default='', max_length=50)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_products', to='categories.HomepageSection')),
            ],
            options={
                'verbose_name': 'Homepage Section Product',
                'verbose_name_plural': 'Homepage Section Products',
                'db_table': 'tbl_homepage_section_products',
                'ordering': ['ordering'],
            },
        ),
    ]
