# Generated by Django 2.2 on 2026-07-10 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0011_products_weight'),
        ('categories', '0014_homepagesectionproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesectionproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homepage_sections', to='product_management.Products'),
        ),
    ]
