# Generated by Django 2.2 on 2026-07-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0015_homepagesectionproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesection',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='homepage_videos/'),
        ),
        migrations.AlterField(
            model_name='homepagesectionproduct',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
