# Generated by Django 2.2 on 2026-07-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0016_auto_20260715_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('categories.homepagesection',),
        ),
        migrations.AlterModelOptions(
            name='homepagesectionproduct',
            options={'verbose_name': 'Product & Category Tags', 'verbose_name_plural': 'Product & Category Tags'},
        ),
        migrations.AlterModelOptions(
            name='producttags',
            options={},
        ),
        migrations.RemoveField(
            model_name='homepagesectionproduct',
            name='product',
        ),
        migrations.AlterField(
            model_name='homepagesectionproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage_products/'),
        ),
        migrations.AlterModelTable(
            name='homepagesectionproduct',
            table='tbl_category_product_tags',
        ),
        migrations.AlterModelTable(
            name='producttags',
            table=None,
        ),
    ]
