# Generated by Django 2.2 on 2026-07-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0017_auto_20260715_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagesectionproduct',
            options={'ordering': ['ordering'], 'verbose_name': 'Homepage Section Product', 'verbose_name_plural': 'Homepage Section Products'},
        ),
        migrations.AlterModelTable(
            name='homepagesectionproduct',
            table='tbl_homepage_section_products',
        ),
    ]
