# Generated by Django 2.2 on 2026-07-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0019_add_product_fk_homepagesectionproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroBanner',
        ),
        migrations.AlterModelOptions(
            name='producttags',
            options={'verbose_name': 'Product & Category Tags', 'verbose_name_plural': 'Product & Category Tags'},
        ),
        migrations.RemoveField(
            model_name='homepagesection',
            name='video',
        ),
        migrations.AlterField(
            model_name='homepagesectionproduct',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterModelTable(
            name='producttags',
            table='tbl_category_product_tags',
        ),
    ]
