# Generated by Django 2.2 on 2026-07-15 17:39

import categories.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0020_auto_20260715_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Label for admin reference (e.g. Summer Sale Banner)', max_length=255)),
                ('video', models.FileField(help_text='Upload .mp4 video file', upload_to=categories.models.upload_hero_banner_video)),
                ('ordering', models.PositiveIntegerField(default=0, help_text='Order in carousel (0 = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(blank=True, help_text='Link to a Homepage Section to show its products as cards when this banner plays', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_banners', to='categories.HomepageSection')),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
                'db_table': 'tbl_hero_banner',
                'ordering': ['ordering'],
            },
        ),
    ]
