# Generated by Django 2.2 on 2026-09-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0014_homepagesection_bestseller'),
        ('categories', '0022_herobannerproduct'),
    ]

    operations = [
    ]
