# Generated by Django 2.2 on 2026-09-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0023_merge_20260904_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesection',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Promotions Banner: animated/static background (webp)', null=True, upload_to='homepage/promotions/'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='products_image',
            field=models.ImageField(blank=True, help_text='Promotions Banner: floating sticker products image', null=True, upload_to='homepage/promotions/'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Promotions Banner: girl/person image', null=True, upload_to='homepage/promotions/'),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero Banner'), ('product_grid', 'Product Grid'), ('promotional_banner', 'Promotional Banner'), ('cute_collection', 'Cute Collection'), ('customers_top_choice', 'Customers Top Choice'), ('cute_collection_cards', 'Cute Collection Cards'), ('dream_box_collections', 'Dream Box Collections'), ('testimonials', 'Testimonials'), ('upgrade_essentials', 'Upgrade Essentials'), ('bestseller', 'Bestseller'), ('promotions_banner', 'Promotions Banner')], max_length=50),
        ),
    ]
