# Generated by Django 2.2 on 2026-09-04 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0024_auto_20260904_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('background_image', models.ImageField(blank=True, help_text='Slide background (animated/static webp)', null=True, upload_to='homepage/promotions/slides/')),
                ('profile_image', models.ImageField(blank=True, help_text='Girl/person image', null=True, upload_to='homepage/promotions/slides/')),
                ('products_image', models.ImageField(blank=True, help_text='Floating sticker products image', null=True, upload_to='homepage/promotions/slides/')),
                ('link_url', models.CharField(blank=True, default='', max_length=500)),
                ('link_text', models.CharField(blank=True, default='Shop Now', max_length=100)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_slides', to='categories.HomepageSection')),
            ],
            options={
                'verbose_name': 'Promotion Slide',
                'verbose_name_plural': 'Promotion Slides',
                'db_table': 'tbl_promotion_slides',
                'ordering': ['ordering'],
            },
        ),
    ]
