# Generated by Django 2.2 on 2020-04-20 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(help_text='User Identification Key', max_length=40, primary_key=True, serialize=False)),
                ('client', models.CharField(help_text='Unique identify system id', max_length=255)),
                ('device_token', models.TextField(blank=True, help_text='For Push Notification Device id', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'db_table': 'tbl_auth_token',
                'unique_together': {('user', 'client')},
            },
        ),
    ]
