# Generated by Django 2.2 on 2020-04-18 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_code', models.CharField(max_length=12, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('payout', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('payout_details', models.TextField(blank=True, null=True)),
                ('affiliate_process', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offer_image')),
                ('video', models.FileField(blank=True, null=True, upload_to='offer_video')),
                ('document', models.FileField(blank=True, null=True, upload_to='offer_document')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Offers & Coupon',
                'verbose_name_plural': 'Offers & Coupons',
                'db_table': 'tbl_offers',
            },
        ),
    ]
