# Generated by Django 2.2 on 2020-08-01 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='payout',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Offer Percentage'),
        ),
    ]
