# Generated by Django 2.2 on 2021-02-20 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0016_auto_20210215_1625'),
        ('affiliate_management', '0011_auto_20200803_1519'),
        ('offers_management', '0002_auto_20200801_1727'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offers',
            new_name='Coupon',
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Coupon', 'verbose_name_plural': 'Coupons'},
        ),
        migrations.AlterModelTable(
            name='coupon',
            table='tbl_coupons',
        ),
    ]
