# Generated by Django 2.2 on 2021-02-20 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_auto_20210129_2348'),
        ('product_management', '0009_auto_20210129_2348'),
        ('offers_management', '0003_auto_20210220_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(2, 'Buy More & Get Free')])),
                ('title', models.CharField(max_length=120)),
                ('min_product', models.PositiveIntegerField(default=1)),
                ('offer_value', models.PositiveIntegerField(default=0)),
                ('max_discount', models.PositiveIntegerField(blank=True, null=True)),
                ('short_descriptions', models.CharField(max_length=256)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='categories_offers', to='categories.Categories')),
                ('products', models.ManyToManyField(blank=True, related_name='product_offers', to='product_management.Products')),
            ],
            options={
                'verbose_name': 'Product Offers',
                'verbose_name_plural': 'Offers',
                'db_table': 'tbl_offers',
            },
        ),
        migrations.CreateModel(
            name='OfferTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='offers_management.Offers')),
            ],
            options={
                'verbose_name': 'Offer Term',
                'verbose_name_plural': 'Offer Terms',
                'db_table': 'tbl_offer_terms',
            },
        ),
    ]
