# Generated by Django 2.2 on 2021-06-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_management', '0004_offers_offerterms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='offer_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
