# Generated by Django 2.2 on 2020-04-19 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=12, unique=True)),
                ('token_description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders_management.Orders')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'db_table': 'tbl_tokens',
            },
        ),
        migrations.CreateModel(
            name='TokenState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Token State',
                'verbose_name_plural': 'Token States',
                'db_table': 'tbl_token_state',
            },
        ),
        migrations.CreateModel(
            name='TokenType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Token Type',
                'verbose_name_plural': 'Token Type',
                'db_table': 'tbl_token_type',
            },
        ),
        migrations.CreateModel(
            name='TokenHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokens_management.Token')),
            ],
            options={
                'verbose_name': 'Token History',
                'verbose_name_plural': 'Token History',
                'db_table': 'tbl_token_history',
            },
        ),
        migrations.AddField(
            model_name='token',
            name='token_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokens_management.TokenState'),
        ),
        migrations.AddField(
            model_name='token',
            name='token_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokens_management.TokenType'),
        ),
    ]
