# Generated by Django 2.2 on 2020-07-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenhistory',
            options={'verbose_name': 'Token History', 'verbose_name_plural': '1. Token History'},
        ),
    ]
