# Generated by Django 2.2 on 2020-08-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens_management', '0002_auto_20200719_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'verbose_name': 'Token', 'verbose_name_plural': '1. Tokens'},
        ),
        migrations.AlterModelOptions(
            name='tokentype',
            options={'verbose_name': 'Token Type', 'verbose_name_plural': '2. Token Type'},
        ),
        migrations.AddField(
            model_name='token',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
