# Generated by Django 2.2 on 2020-08-02 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens_management', '0003_auto_20200801_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTokens',
            fields=[
            ],
            options={
                'verbose_name': 'New Tokens',
                'verbose_name_plural': '1. New Tokens',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tokens_management.token',),
        ),
        migrations.CreateModel(
            name='ResolvedTokens',
            fields=[
            ],
            options={
                'verbose_name': 'Resolved Tokens',
                'verbose_name_plural': '2. Resolved Tokens',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tokens_management.token',),
        ),
        migrations.AlterModelOptions(
            name='tokentype',
            options={'verbose_name': 'Token Type', 'verbose_name_plural': '3. Token Type'},
        ),
    ]
