# Generated by Django 2.2 on 2021-02-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0002_auto_20200720_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_offer',
            field=models.BooleanField(default=False),
        ),
    ]
