# Generated by Django 2.2 on 2021-10-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0003_cart_is_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color_code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
