# Generated by Django 2.2 on 2026-07-15 16:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0013_remove_products_is_hero_featured'),
        ('cart_management', '0004_cart_color_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9)])),
                ('is_offer', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('color_code', models.CharField(blank=True, max_length=256, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.Products')),
            ],
            options={
                'verbose_name': 'Guest Cart',
                'verbose_name_plural': 'Guest Cart',
                'db_table': 'tbl_guest_cart',
                'unique_together': {('session_id', 'product')},
            },
        ),
    ]
