# Generated by Django 2.2 on 2020-10-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0002_masterhtml'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('token', models.TextField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Shipment Login',
                'verbose_name_plural': 'Shipment Login',
                'db_table': 'tbl_shipment_login',
            },
        ),
    ]
