# Generated by Django 2.2 on 2026-07-15 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_management', '0012_products_is_hero_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('video', models.FileField(upload_to='hero_videos/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Playback order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroVideoProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.Products')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='hero.HeroVideo')),
            ],
            options={
                'unique_together': {('video', 'product')},
            },
        ),
    ]
