# Generated by Django 2.2 on 2026-07-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herovideo',
            options={'ordering': ['order'], 'verbose_name': 'Herobanner', 'verbose_name_plural': 'Herobanners'},
        ),
    ]
